fixtures:
  repositories:
    beaver: git://github.com/evenup/evenup-beaver.git
    concat: git://github.com/ripienaar/puppet-concat.git
    logrotate: https://github.com/evenup/evenup-logrotate.git
    ruby: git://github.com/evenup/evenup-ruby.git
    sensu: git://github.com/sensu/sensu-puppet.git
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
  symlinks:
    apache: "#{source_dir}"

