---
language: ruby
bundler_args: --without development
script: "bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--format documentation'"
matrix:
  fast_finish: true
  include:
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 2.7.0"
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.1.0"
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.2.0"
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.3.0"
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.4.0"
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.5.0"
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.6.0"
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.7.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.1.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.2.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.3.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.4.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.5.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.6.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.7.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.2.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.4.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.5.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.6.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.7.0"
  - rvm: 2.1.0
    env: PUPPET_GEM_VERSION="~> 3.5.0"
  - rvm: 2.1.0
    env: PUPPET_GEM_VERSION="~> 3.6.0"
  - rvm: 2.1.0
    env: PUPPET_GEM_VERSION="~> 3.7.0"
notifications:
  email: false
  hipchat:
    rooms:
      - secure: dpF/KF4dTsYh2tkBpxCg5jCYSie+ge+IsUAcwiCfqdVGOqFs8LyaJvHzObVA\naF6up/OFLjRtt979ht9dgUZUHEvbZk0iQpbojSRng8CWJUNobXVE1cLh1HKg\nkTh9NlUu1hu0Eyk139OMZo1bC4nmN83yCBnclymgWnNaT43FttA=
  on_success: always
  on_failure: always
