name 'evenup-apache'
version '3.2.0'
author 'Justin Lambert <jlambert@letsevenup.com>'
license 'Apache'
summary 'Manages apache including ajp proxy, thin proxy, and mod_security.'
description 'Installs, configures, and runs the apache service.  Maintains module config files and vhosts.'
project_page 'https://github.com/evenup/evenup-apache'
dependency 'evenup/beaver'
dependency 'puppetlabs/stdlib', '>= 3.2.0'
dependency 'puppetlabs/concat', '>= 0.2.0'

