name 'evenup-apache'
version '2.0.0'
author 'Justin Lambert <jlambert@letsevenup.com>'
license 'Apache'
summary 'Manages apache.'
description 'Installs, configures, and runs the apache service.  Maintains module config files and vhosts.'
project_page 'https://github.com/evenup/evenup-apache'
dependency 'evenup/logrotate', '>= 1.0.0'
dependency 'evenup/beaver'
dependency 'puppetlabs/stdlib', '>= 3.2.0'
dependency 'ripienaar/concat', '>= 0.2.0'
